apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-server
  namespace: default

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hello-server

  template:
    metadata:
      labels:
        app: hello-server

    spec:
      containers:
        - name: hello-server
          image: zoleman/hello-server:latest
          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1