name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

env:
  IMAGE_REPOSITORY: ${{ vars.IMAGE_REPOSITORY }}
  APP_PORT: ${{ vars.APP_PORT }}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run Go tests
        run: go test ./...

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
            docker build \
              --build-arg APP_USER=$APP_USER \
              -t $IMAGE_REPOSITORY:${{ github.sha }} \
              .

      - name: Run container
        run: |
          docker run -d \
            --name hello-server-test \
            -e APP_PORT=$APP_PORT \
            -p $APP_PORT:$APP_PORT \
            $IMAGE_REPOSITORY:${{ github.sha }}

      - name: Test health endpoint
        run: curl --fail --retry 10 --retry-delay 1 --retry-connrefused http://localhost:$APP_PORT/health

      - name: Stop container
        if: always()
        run: docker rm -f hello-server-test

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push $IMAGE_REPOSITORY:${{ github.sha }}
          docker tag $IMAGE_REPOSITORY:${{ github.sha }} $IMAGE_REPOSITORY:latest
          docker push $IMAGE_REPOSITORY:latest